### ISSUE TITLE
Send max/entire amount

### ISSUE THREAD

**Issue by michaelScoff** [TrustWallet/trust-wallet-ios#204]

**Comment by colourful-land** [comment]
This issue is related to #33 

Also I think more important than sending the entire amount, the app should show the current available balance in Ether. Currently the app (on my iphone) shows only the current balance in USD value, and ask me to type the Ether value so I propose we repurpose this issue to the display of Ether balance along side where user types the number of Ethers to send.

**Comment by michaelScoff** [comment]
@colourful-land currently balance available in the header, so you can see it! 
If you use max/entire balance button then it will appear all the ether that you have.

**Comment by michaelScoff** [comment]
Closing this in favor of https://github.com/TrustWallet/trust-wallet-ios/issues/33
