### ISSUE TITLE
Generate QR code quicker

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/trust-wallet-ios#783]
The current solution is too slow! It should be instant

**Comment by BloodyPixy** [comment]
@vikmeup in most cases the QR is generated in less than 0.6 sec. Are we talking about iOS 11.4 or 12? Could you please add some more information regarding the issue and the way to reproduce?

**Comment by vikmeup** [comment]
@BloodyPixy 0.6 is a lot! This should be instant. Let's try `.userInitiated`

**Comment by BloodyPixy** [comment]
I will use `.userInteractive` - "returns a global concurrent queue which is suitable for task that need to be done "quickly" in order to update the user interface. Tasks on this queue have a higher priority than e.g. tasks on a  QOS_CLASS_BACKGROUND queue. But this is not the main queue." I believe it is what we need and it seems to work much faster on real iPhone 5s (Not worth comparing on simulator as it uses hardware acceleration of Mac).
