### ISSUE TITLE
Test Net Support 

### ISSUE THREAD

**Issue by lrgeoemtry** [TrustWallet/trust-wallet-ios#919]
im going to raise another issue on this, 
this was the best thing about Trust from developer / sdk level. 

where is the love for the core developer community anymore? 

smh 

at least dont let the api go down. 

currently the https://api.trustwalletapp.com/ ropsten / kovan is down for seemingly no good reason. 

i called this out in the telegram group and got booted / banned for "asking too many questions" in your public forum. 

really bad moves post binance buy and its hurting the developers who make all this happen while the fat cats make money claiming to be experts....

**Comment by vikmeup** [comment]
@lrgeoemtry code is open source for deploying your own node: https://github.com/TrustWallet/trust-ray!

Regarding test networks, we want to focus on shipping features quicker, test network were slowing us down! Since our code is open source you can build our own client with no issue.

I highly recommend for testing to use MetaMask, they are great for dApp development and then it should be accessible via dApp browser.

This decisions were not made based on acquisitions deal.
